//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:N.N.NNNNN.N
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOutput {
using System;

public class ConditionalAttributes {
#line hidden
public ConditionalAttributes() {
}
public override void Execute() {

#line 1 "ConditionalAttributes.cshtml"
  
    var ch = true;
    var cls = "bar";


#line default
#line hidden
WriteLiteral("    <a");

WriteLiteral(" href=\"Foo\"");

WriteLiteral(" />\r\n");

WriteLiteral("    <p");

WriteAttribute("class", " class=\"", "\""

#line 5 "ConditionalAttributes.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", cls

#line default
#line hidden
, false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <p");

WriteAttribute("class", " class=\"", "\""
, Tuple.Create("", "foo", true)

#line 6 "ConditionalAttributes.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>(" ", cls

#line default
#line hidden
, false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <p");

WriteAttribute("class", " class=\"", "\""

#line 7 "ConditionalAttributes.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", cls

#line default
#line hidden
, false)
, Tuple.Create(" ", "foo", true)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("checked", " checked=\"", "\""

#line 8 "ConditionalAttributes.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", ch

#line default
#line hidden
, false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("checked", " checked=\"", "\""
, Tuple.Create("", "foo", true)

#line 9 "ConditionalAttributes.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>(" ", ch

#line default
#line hidden
, false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <p");

WriteAttribute("class", " class=\"", "\""
, Tuple.Create<System.String, System.Object, System.Boolean>("", new Template(__razor_attribute_value_writer => {


#line 10 "ConditionalAttributes.cshtml"
               if(cls != null) { 

#line default
#line hidden

#line 10 "ConditionalAttributes.cshtml"
WriteTo(__razor_attribute_value_writer, cls);


#line default
#line hidden

#line 10 "ConditionalAttributes.cshtml"
                                      }

#line default
#line hidden
}), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Foo")
, false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <script");

WriteAttribute("src", " src=\"", "\""

#line 12 "ConditionalAttributes.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", Url.Content("~/Scripts/jquery-1.6.2.min.js")

#line default
#line hidden
, false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", " src=\"", "\""

#line 13 "ConditionalAttributes.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")

#line default
#line hidden
, false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteLiteral(" src=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.16/jquery-ui.min.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");


#line 15 "ConditionalAttributes.cshtml"


#line default
#line hidden
}
}
}
