//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:N.N.NNNNN.N
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOutput {
using System;

public class HtmlCommentWithQuote_Single {
#line hidden
public HtmlCommentWithQuote_Single() {
}
public override void Execute() {
WriteLiteral("<!-- \' -->\r\n<img");

WriteAttribute("src", " src=\"", "\""
, Tuple.Create("", Href("~/images/submit.png")
, false)
);

WriteLiteral(" />");

}
}
}
