//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:N.N.NNNNN.N
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOutput {
using System;

public class InlineBlocks {
#line hidden
#line 1 "InlineBlocks.cshtml"
public static Template Link(string link) {
#line default
#line hidden
return new Template(__razor_helper_writer => {

#line 1 "InlineBlocks.cshtml"
                           


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <a");

WriteAttributeTo(__razor_helper_writer, "href", " href=\"", "\""
, Tuple.Create<System.String, System.Object, System.Boolean>("", new Template(__razor_attribute_value_writer => {


#line 2 "InlineBlocks.cshtml"
              if(link != null) { 

#line default
#line hidden

#line 2 "InlineBlocks.cshtml"
WriteTo(__razor_attribute_value_writer, link);


#line default
#line hidden

#line 2 "InlineBlocks.cshtml"
                                       } else {

#line default
#line hidden
WriteLiteralTo(__razor_attribute_value_writer, " ");

WriteLiteralTo(__razor_attribute_value_writer, "#");

WriteLiteralTo(__razor_attribute_value_writer, " ");


#line 2 "InlineBlocks.cshtml"
                                                               }

#line default
#line hidden
}), false)
);

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 3 "InlineBlocks.cshtml"


#line default
#line hidden
});

#line 3 "InlineBlocks.cshtml"
}
#line default
#line hidden

public InlineBlocks() {
}
public override void Execute() {
}
}
}
