//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:N.N.NNNNN.N
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOutput {
using System;

public class ResolveUrl {
#line hidden
public ResolveUrl() {
}
public override void Execute() {
WriteLiteral("<a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Foo")
, false)
);

WriteLiteral(">Foo</a>\r\n<a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Products/")
, false)

#line 2 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
);

WriteLiteral(">");


#line 2 "ResolveUrl.cshtml"
                            Write(product.Name);


#line default
#line hidden
WriteLiteral("</a>\r\n<a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Products/")
, false)

#line 3 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
, Tuple.Create("", "/Detail", true)
);

WriteLiteral(">Details</a>\r\n<a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/A+Really(Crazy),Url.Is:This/")
, false)

#line 4 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
, Tuple.Create("", "/Detail", true)
);

WriteLiteral(">Crazy Url!</a>\r\n\r\n");


#line 6 "ResolveUrl.cshtml"
  


#line default
#line hidden
WriteLiteral("    ");

WriteLiteral("\r\n        <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Foo")
, false)
);

WriteLiteral(">Foo</a>\r\n        <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Products/")
, false)

#line 9 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
);

WriteLiteral(">");


#line 9 "ResolveUrl.cshtml"
                                    Write(product.Name);


#line default
#line hidden
WriteLiteral("</a>\r\n        <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Products/")
, false)

#line 10 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
, Tuple.Create("", "/Detail", true)
);

WriteLiteral(">Details</a>\r\n        <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/A+Really(Crazy),Url.Is:This/")
, false)

#line 11 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
, Tuple.Create("", "/Detail", true)
);

WriteLiteral(">Crazy Url!</a>\r\n    ");

WriteLiteral("\r\n");


#line 13 "ResolveUrl.cshtml"


#line default
#line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Foo", () => {

WriteLiteral("\r\n    <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Foo")
, false)
);

WriteLiteral(">Foo</a>\r\n    <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Products/")
, false)

#line 17 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
);

WriteLiteral(">");


#line 17 "ResolveUrl.cshtml"
                                Write(product.Name);


#line default
#line hidden
WriteLiteral("</a>\r\n    <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/Products/")
, false)

#line 18 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
, Tuple.Create("", "/Detail", true)
);

WriteLiteral(">Details</a>\r\n    <a");

WriteAttribute("href", " href=\"", "\""
, Tuple.Create("", Href("~/A+Really(Crazy),Url.Is:This/")
, false)

#line 19 "ResolveUrl.cshtml"
, Tuple.Create<System.String, System.Object, System.Boolean>("", product.id

#line default
#line hidden
, false)
, Tuple.Create("", "/Detail", true)
);

WriteLiteral(">Crazy Url!</a>\r\n");

});

}
}
}
